spring:
  jpa:
    show-sql: false

logging:
  level:
    root: WARN
    me.timur.secondhanduz: INFO
    org.springframework.security: WARN

server:
  error:
    include-message: never
    include-binding-errors: never
    include-stacktrace: never

management:
  endpoint:
    health:
      show-details: never
